# El service para referenciar al elastic search
apiVersion: v1
kind: Service
metadata:
  name: search-service-elasticsearch
spec:
  clusterIP: None  # Headless Service (requerido para StatefulSet)
  selector:
    app: search-service-elasticsearch
  ports:
    - port: 9200
      targetPort: 9200

---

# El despliegue persistente de elastic search para preservar los datos en el tiempo
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: search-service-elasticsearch
spec:
  serviceName: search-service-elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: search-service-elasticsearch
  template:
    metadata:
      labels:
        app: search-service-elasticsearch
    spec:
      securityContext:
        fsGroup: 1000        # ðŸ‘ˆ Da permisos al contenedor para escribir en el volumen
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
        ports:
        - containerPort: 9200
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"       # ðŸ”¹ Aumentamos el heap a 1 GB
        - name: xpack.security.enabled
          value: "false"
        - name: discovery.type
          value: "single-node"
        resources:
          requests:
            cpu: "250m"               # reserva 1/4 de CPU
            memory: "1Gi"             # ðŸ”¹ solicita 1 GB como mÃ­nimo
          limits:
            cpu: "500m"               # puede usar hasta 1/2 CPU
            memory: "2Gi"             # ðŸ”¹ puede usar hasta 2 GB mÃ¡ximo
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi