services:
  test_runner:
    build:
      context: .
      dockerfile: Dockerfiletest
    container_name: mi_test_runner
    volumes:
      - .:/app
      
    command: python -m unittest discover -s tests -t . -v
    
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      RABBITMQ_HOST: "message-broker"
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    
    depends_on:
      elasticsearch:
        condition: service_healthy
    
    networks:
      - test_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch_test
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -E '\"status\":\"(green|yellow)\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - test_network

networks:
  test_network:
    driver: bridge