apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: search-service-ingress
spec:
  tls:
  - hosts:
    - search-service.inf326.cl
    secretName: search-service-tls
  ingressClassName: nginx
  rules:
  - host: search-service.inf326.cl
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: search-service
              port:
                number: 8000
  